# Generated by Django 2.2.24 on 2022-10-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='disable',
        ),
    ]
