# Generated by Django 2.2.24 on 2022-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_remove_keyword_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
