# Generated by Django 2.2.24 on 2022-10-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0003_keyword_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='name',
        ),
    ]
