# Generated by Django 2.2.24 on 2022-10-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_remove_athleteprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
