# Generated by Django 2.2.24 on 2022-10-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0002_delete_followedcommunity'),
        ('youtube_app', '0005_athleteprofile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityProfile',
        ),
        migrations.DeleteModel(
            name='CommunityProfileCategory',
        ),
    ]
