# Generated by Django 2.2.24 on 2022-10-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0004_delete_followedcommunity'),
        ('youtube_app', '0007_communityprofile_communityprofilecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityProfile',
        ),
        migrations.DeleteModel(
            name='CommunityProfileCategory',
        ),
    ]
