# Generated by Django 2.2.24 on 2022-10-01 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=300)),
                ('video_description', models.CharField(max_length=1000)),
                ('video_id', models.CharField(max_length=20)),
                ('channel_title', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=100)),
                ('channel_profile_pic', models.CharField(max_length=100)),
                ('video_thumbnail_pic', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.Keyword')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowedCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.CommunityProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Community',
                'verbose_name_plural': 'Followed Community',
            },
        ),
        migrations.CreateModel(
            name='FollowedAthletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.AthleteProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Athlete',
                'verbose_name_plural': 'Followed Athletes',
            },
        ),
    ]
