# Generated by Django 2.2.24 on 2022-10-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_app', '0007_communityprofile_communityprofilecategory'),
        ('users_data', '0002_delete_followedcommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.CommunityProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Community',
                'verbose_name_plural': 'Followed Community',
            },
        ),
    ]
