# Generated by Django 2.2.24 on 2022-10-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0003_followedcommunity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowedCommunity',
        ),
    ]
